# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
default:
  tags:
    - docker

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

.apt_dependencies: &apt_dependencies
  - echo "Installing dependencies..."
  - apt update
  - apt install -y --no-install-recommends gcc g++ make cmake diffutils
  - echo "Installing dependencies complete."

.build_step: &build_step
  - echo "Compiling the code..."
  - mkdir build-debug
  - cd build-debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make -j$(nproc)
  - make -j$(nproc) test
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(nproc)
  - make -j$(nproc) test
  - echo "Compile complete."

build-debian:
  stage: build
  image: debian:latest
  tags:
    - docker
    - x86_64
  script:
    - *apt_dependencies
    - *build_step
  artifacts:
    when: always
    paths:
      - /builds/edward/farewell-to-king/build/libfarewelltoking.a
      - /builds/edward/farewell-to-king/build/farewelltoking-test
      - /builds/edward/farewell-to-king/build/Testing/Temporary/LastTest.log
      - /builds/edward/farewell-to-king/build-debug/libfarewelltoking.a
      - /builds/edward/farewell-to-king/build-debug/farewelltoking-test
      - /builds/edward/farewell-to-king/build-debug/Testing/Temporary/LastTest.log

build-debian-arm64:
  stage: build
  image: debian:latest
  tags:
    - docker
    - arm64
  script:
    - *apt_dependencies
    - *build_step
  artifacts:
    when: always
    paths:
      - /builds/edward/farewell-to-king/build/libfarewelltoking.a
      - /builds/edward/farewell-to-king/build/farewelltoking-test
      - /builds/edward/farewell-to-king/build/Testing/Temporary/LastTest.log
      - /builds/edward/farewell-to-king/build-debug/libfarewelltoking.a
      - /builds/edward/farewell-to-king/build-debug/farewelltoking-test
      - /builds/edward/farewell-to-king/build-debug/Testing/Temporary/LastTest.log

build-ubuntu:
  stage: build
  image: ubuntu:latest
  script:
    - *apt_dependencies
    - *build_step
  artifacts:
    when: always
    paths:
      - /builds/edward/farewell-to-king/build/libfarewelltoking.a
      - /builds/edward/farewell-to-king/build/farewelltoking-test
      - /builds/edward/farewell-to-king/build/Testing/Temporary/LastTest.log
      - /builds/edward/farewell-to-king/build-debug/libfarewelltoking.a
      - /builds/edward/farewell-to-king/build-debug/farewelltoking-test
      - /builds/edward/farewell-to-king/build-debug/Testing/Temporary/LastTest.log

build-fedora:
  stage: build
  image: fedora:latest
  script:
    - echo "Installing dependencies..."
    - dnf install -y gcc gcc-c++ cmake diffutils
    - echo "Installing dependencies complete."
    - *build_step
  artifacts:
    when: always
    paths:
      - /builds/edward/farewell-to-king/build/libfarewelltoking.a
      - /builds/edward/farewell-to-king/build/farewelltoking-test
      - /builds/edward/farewell-to-king/build/Testing/Temporary/LastTest.log
      - /builds/edward/farewell-to-king/build-debug/libfarewelltoking.a
      - /builds/edward/farewell-to-king/build-debug/farewelltoking-test
      - /builds/edward/farewell-to-king/build-debug/Testing/Temporary/LastTest.log

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  tags:
  - docker
  - x86_64