# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake.exe

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/Users/edward/Desktop/FlyByKnightLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/Users/edward/Desktop/FlyByKnightLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/edward/Desktop/FlyByKnightLib/CMakeFiles /cygdrive/c/Users/edward/Desktop/FlyByKnightLib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/edward/Desktop/FlyByKnightLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named farewelltoking

# Build rule for target.
farewelltoking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 farewelltoking
.PHONY : farewelltoking

# fast build rule for target.
farewelltoking/fast:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/build
.PHONY : farewelltoking/fast

#=============================================================================
# Target rules for targets named farewelltokingstr

# Build rule for target.
farewelltokingstr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 farewelltokingstr
.PHONY : farewelltokingstr

# fast build rule for target.
farewelltokingstr/fast:
	$(MAKE) -f CMakeFiles/farewelltokingstr.dir/build.make CMakeFiles/farewelltokingstr.dir/build
.PHONY : farewelltokingstr/fast

#=============================================================================
# Target rules for targets named farewelltokingtest

# Build rule for target.
farewelltokingtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 farewelltokingtest
.PHONY : farewelltokingtest

# fast build rule for target.
farewelltokingtest/fast:
	$(MAKE) -f CMakeFiles/farewelltokingtest.dir/build.make CMakeFiles/farewelltokingtest.dir/build
.PHONY : farewelltokingtest/fast

FarewellToKing.o: FarewellToKing.c.o
.PHONY : FarewellToKing.o

# target to build an object file
FarewellToKing.c.o:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/FarewellToKing.c.o
.PHONY : FarewellToKing.c.o

FarewellToKing.i: FarewellToKing.c.i
.PHONY : FarewellToKing.i

# target to preprocess a source file
FarewellToKing.c.i:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/FarewellToKing.c.i
.PHONY : FarewellToKing.c.i

FarewellToKing.s: FarewellToKing.c.s
.PHONY : FarewellToKing.s

# target to generate assembly for a file
FarewellToKing.c.s:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/FarewellToKing.c.s
.PHONY : FarewellToKing.c.s

FarewellToKingBoard.o: FarewellToKingBoard.c.o
.PHONY : FarewellToKingBoard.o

# target to build an object file
FarewellToKingBoard.c.o:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/FarewellToKingBoard.c.o
.PHONY : FarewellToKingBoard.c.o

FarewellToKingBoard.i: FarewellToKingBoard.c.i
.PHONY : FarewellToKingBoard.i

# target to preprocess a source file
FarewellToKingBoard.c.i:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/FarewellToKingBoard.c.i
.PHONY : FarewellToKingBoard.c.i

FarewellToKingBoard.s: FarewellToKingBoard.c.s
.PHONY : FarewellToKingBoard.s

# target to generate assembly for a file
FarewellToKingBoard.c.s:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/FarewellToKingBoard.c.s
.PHONY : FarewellToKingBoard.c.s

FarewellToKingMask.o: FarewellToKingMask.c.o
.PHONY : FarewellToKingMask.o

# target to build an object file
FarewellToKingMask.c.o:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/FarewellToKingMask.c.o
.PHONY : FarewellToKingMask.c.o

FarewellToKingMask.i: FarewellToKingMask.c.i
.PHONY : FarewellToKingMask.i

# target to preprocess a source file
FarewellToKingMask.c.i:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/FarewellToKingMask.c.i
.PHONY : FarewellToKingMask.c.i

FarewellToKingMask.s: FarewellToKingMask.c.s
.PHONY : FarewellToKingMask.s

# target to generate assembly for a file
FarewellToKingMask.c.s:
	$(MAKE) -f CMakeFiles/farewelltoking.dir/build.make CMakeFiles/farewelltoking.dir/FarewellToKingMask.c.s
.PHONY : FarewellToKingMask.c.s

FarewellToKingStr.o: FarewellToKingStr.c.o
.PHONY : FarewellToKingStr.o

# target to build an object file
FarewellToKingStr.c.o:
	$(MAKE) -f CMakeFiles/farewelltokingstr.dir/build.make CMakeFiles/farewelltokingstr.dir/FarewellToKingStr.c.o
.PHONY : FarewellToKingStr.c.o

FarewellToKingStr.i: FarewellToKingStr.c.i
.PHONY : FarewellToKingStr.i

# target to preprocess a source file
FarewellToKingStr.c.i:
	$(MAKE) -f CMakeFiles/farewelltokingstr.dir/build.make CMakeFiles/farewelltokingstr.dir/FarewellToKingStr.c.i
.PHONY : FarewellToKingStr.c.i

FarewellToKingStr.s: FarewellToKingStr.c.s
.PHONY : FarewellToKingStr.s

# target to generate assembly for a file
FarewellToKingStr.c.s:
	$(MAKE) -f CMakeFiles/farewelltokingstr.dir/build.make CMakeFiles/farewelltokingstr.dir/FarewellToKingStr.c.s
.PHONY : FarewellToKingStr.c.s

FarewellToKingTest.o: FarewellToKingTest.c.o
.PHONY : FarewellToKingTest.o

# target to build an object file
FarewellToKingTest.c.o:
	$(MAKE) -f CMakeFiles/farewelltokingtest.dir/build.make CMakeFiles/farewelltokingtest.dir/FarewellToKingTest.c.o
.PHONY : FarewellToKingTest.c.o

FarewellToKingTest.i: FarewellToKingTest.c.i
.PHONY : FarewellToKingTest.i

# target to preprocess a source file
FarewellToKingTest.c.i:
	$(MAKE) -f CMakeFiles/farewelltokingtest.dir/build.make CMakeFiles/farewelltokingtest.dir/FarewellToKingTest.c.i
.PHONY : FarewellToKingTest.c.i

FarewellToKingTest.s: FarewellToKingTest.c.s
.PHONY : FarewellToKingTest.s

# target to generate assembly for a file
FarewellToKingTest.c.s:
	$(MAKE) -f CMakeFiles/farewelltokingtest.dir/build.make CMakeFiles/farewelltokingtest.dir/FarewellToKingTest.c.s
.PHONY : FarewellToKingTest.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... farewelltoking"
	@echo "... farewelltokingstr"
	@echo "... farewelltokingtest"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... FarewellToKing.o"
	@echo "... FarewellToKing.i"
	@echo "... FarewellToKing.s"
	@echo "... FarewellToKingBoard.o"
	@echo "... FarewellToKingBoard.i"
	@echo "... FarewellToKingBoard.s"
	@echo "... FarewellToKingMask.o"
	@echo "... FarewellToKingMask.i"
	@echo "... FarewellToKingMask.s"
	@echo "... FarewellToKingStr.o"
	@echo "... FarewellToKingStr.i"
	@echo "... FarewellToKingStr.s"
	@echo "... FarewellToKingTest.o"
	@echo "... FarewellToKingTest.i"
	@echo "... FarewellToKingTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

