# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake.exe

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/Users/edward/Desktop/FlyByKnightLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/Users/edward/Desktop/FlyByKnightLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/edward/Desktop/FlyByKnightLib/CMakeFiles /cygdrive/c/Users/edward/Desktop/FlyByKnightLib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/edward/Desktop/FlyByKnightLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flybyknightlib

# Build rule for target.
flybyknightlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flybyknightlib
.PHONY : flybyknightlib

# fast build rule for target.
flybyknightlib/fast:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/build
.PHONY : flybyknightlib/fast

#=============================================================================
# Target rules for targets named flybyknightlibstr

# Build rule for target.
flybyknightlibstr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flybyknightlibstr
.PHONY : flybyknightlibstr

# fast build rule for target.
flybyknightlibstr/fast:
	$(MAKE) -f CMakeFiles/flybyknightlibstr.dir/build.make CMakeFiles/flybyknightlibstr.dir/build
.PHONY : flybyknightlibstr/fast

#=============================================================================
# Target rules for targets named flybyknightlibtest

# Build rule for target.
flybyknightlibtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flybyknightlibtest
.PHONY : flybyknightlibtest

# fast build rule for target.
flybyknightlibtest/fast:
	$(MAKE) -f CMakeFiles/flybyknightlibtest.dir/build.make CMakeFiles/flybyknightlibtest.dir/build
.PHONY : flybyknightlibtest/fast

flyByKnightLib.o: flyByKnightLib.c.o
.PHONY : flyByKnightLib.o

# target to build an object file
flyByKnightLib.c.o:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/flyByKnightLib.c.o
.PHONY : flyByKnightLib.c.o

flyByKnightLib.i: flyByKnightLib.c.i
.PHONY : flyByKnightLib.i

# target to preprocess a source file
flyByKnightLib.c.i:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/flyByKnightLib.c.i
.PHONY : flyByKnightLib.c.i

flyByKnightLib.s: flyByKnightLib.c.s
.PHONY : flyByKnightLib.s

# target to generate assembly for a file
flyByKnightLib.c.s:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/flyByKnightLib.c.s
.PHONY : flyByKnightLib.c.s

flyByKnightLibBoard.o: flyByKnightLibBoard.c.o
.PHONY : flyByKnightLibBoard.o

# target to build an object file
flyByKnightLibBoard.c.o:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/flyByKnightLibBoard.c.o
.PHONY : flyByKnightLibBoard.c.o

flyByKnightLibBoard.i: flyByKnightLibBoard.c.i
.PHONY : flyByKnightLibBoard.i

# target to preprocess a source file
flyByKnightLibBoard.c.i:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/flyByKnightLibBoard.c.i
.PHONY : flyByKnightLibBoard.c.i

flyByKnightLibBoard.s: flyByKnightLibBoard.c.s
.PHONY : flyByKnightLibBoard.s

# target to generate assembly for a file
flyByKnightLibBoard.c.s:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/flyByKnightLibBoard.c.s
.PHONY : flyByKnightLibBoard.c.s

flyByKnightLibMask.o: flyByKnightLibMask.c.o
.PHONY : flyByKnightLibMask.o

# target to build an object file
flyByKnightLibMask.c.o:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/flyByKnightLibMask.c.o
.PHONY : flyByKnightLibMask.c.o

flyByKnightLibMask.i: flyByKnightLibMask.c.i
.PHONY : flyByKnightLibMask.i

# target to preprocess a source file
flyByKnightLibMask.c.i:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/flyByKnightLibMask.c.i
.PHONY : flyByKnightLibMask.c.i

flyByKnightLibMask.s: flyByKnightLibMask.c.s
.PHONY : flyByKnightLibMask.s

# target to generate assembly for a file
flyByKnightLibMask.c.s:
	$(MAKE) -f CMakeFiles/flybyknightlib.dir/build.make CMakeFiles/flybyknightlib.dir/flyByKnightLibMask.c.s
.PHONY : flyByKnightLibMask.c.s

flyByKnightLibStr.o: flyByKnightLibStr.c.o
.PHONY : flyByKnightLibStr.o

# target to build an object file
flyByKnightLibStr.c.o:
	$(MAKE) -f CMakeFiles/flybyknightlibstr.dir/build.make CMakeFiles/flybyknightlibstr.dir/flyByKnightLibStr.c.o
.PHONY : flyByKnightLibStr.c.o

flyByKnightLibStr.i: flyByKnightLibStr.c.i
.PHONY : flyByKnightLibStr.i

# target to preprocess a source file
flyByKnightLibStr.c.i:
	$(MAKE) -f CMakeFiles/flybyknightlibstr.dir/build.make CMakeFiles/flybyknightlibstr.dir/flyByKnightLibStr.c.i
.PHONY : flyByKnightLibStr.c.i

flyByKnightLibStr.s: flyByKnightLibStr.c.s
.PHONY : flyByKnightLibStr.s

# target to generate assembly for a file
flyByKnightLibStr.c.s:
	$(MAKE) -f CMakeFiles/flybyknightlibstr.dir/build.make CMakeFiles/flybyknightlibstr.dir/flyByKnightLibStr.c.s
.PHONY : flyByKnightLibStr.c.s

flyByKnightLibTest.o: flyByKnightLibTest.c.o
.PHONY : flyByKnightLibTest.o

# target to build an object file
flyByKnightLibTest.c.o:
	$(MAKE) -f CMakeFiles/flybyknightlibtest.dir/build.make CMakeFiles/flybyknightlibtest.dir/flyByKnightLibTest.c.o
.PHONY : flyByKnightLibTest.c.o

flyByKnightLibTest.i: flyByKnightLibTest.c.i
.PHONY : flyByKnightLibTest.i

# target to preprocess a source file
flyByKnightLibTest.c.i:
	$(MAKE) -f CMakeFiles/flybyknightlibtest.dir/build.make CMakeFiles/flybyknightlibtest.dir/flyByKnightLibTest.c.i
.PHONY : flyByKnightLibTest.c.i

flyByKnightLibTest.s: flyByKnightLibTest.c.s
.PHONY : flyByKnightLibTest.s

# target to generate assembly for a file
flyByKnightLibTest.c.s:
	$(MAKE) -f CMakeFiles/flybyknightlibtest.dir/build.make CMakeFiles/flybyknightlibtest.dir/flyByKnightLibTest.c.s
.PHONY : flyByKnightLibTest.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... flybyknightlib"
	@echo "... flybyknightlibstr"
	@echo "... flybyknightlibtest"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... flyByKnightLib.o"
	@echo "... flyByKnightLib.i"
	@echo "... flyByKnightLib.s"
	@echo "... flyByKnightLibBoard.o"
	@echo "... flyByKnightLibBoard.i"
	@echo "... flyByKnightLibBoard.s"
	@echo "... flyByKnightLibMask.o"
	@echo "... flyByKnightLibMask.i"
	@echo "... flyByKnightLibMask.s"
	@echo "... flyByKnightLibStr.o"
	@echo "... flyByKnightLibStr.i"
	@echo "... flyByKnightLibStr.s"
	@echo "... flyByKnightLibTest.o"
	@echo "... flyByKnightLibTest.i"
	@echo "... flyByKnightLibTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

